### PR TITLE
Move some vars to defaults

### PR DESCRIPTION
**Pull request by nre-ableton**
- Move some vars to defaults
- Test that ccache_install_prefix works
- Version 0.0.4

### CODE REVIEW

**Comment by nre-ableton** [comment]
Bah, so the CI failure is fixed by 93b53c3, but that will undoubtably make yamllint complain since the line is >90 chars. Rather than worry about a bunch of awkward multi-line YAML stuff, let's instead merge #7 (which makes this line much shorter) and rebase. I've marked this PR as a draft until that happens.

**Comment by nre-ableton** [comment]
@ablbot autosquash

**Comment by nre-ableton** [comment]
Ok, #7 has been merged, so this PR is ready for review.

**Review by rco-ableton — APPROVED** [review]
LGTM 👍

**Pull request merged**
